src/mainpage/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.MainPageView.as_view(), name="index"),
]

src/test_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('tester.urls')),
    path('', include('mainpage.urls')),
]

src/tester/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'tester'

urlpatterns = [
    path('categories/', views.CategoriesView.as_view(), name="categories"),
    path('<slug:category_slug>/', views.TestByCategoryView.as_view(), name="category"),
    path('<slug:category_slug>/<int:pk>/', views.TestDetailView.as_view(), name="test"),
]

src/mainpage/models.py
from django.db import models

src/tester/models.py
from django.db import models
from django.core import exceptions
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.urls import reverse
from pytils.translit import slugify
from django.utils.translation import gettext_lazy as _

class TestCategory(models.Model):
    name = models.CharField(_('Название категории'), max_length=150, unique=True)
    slug = models.SlugField(_('Имя в ссылке'), max_length=150, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tester:test', kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категория тестов'
        verbose_name_plural = 'Категории тестов'
        ordering = ['name']


class TestInstance(models.Model):
    name = models.CharField(_('Тема'), max_length=150)
    description = models.TextField(_('Описание'), blank=True)
    category = models.ForeignKey(TestCategory,
        verbose_name='Категория',
        on_delete=models.CASCADE,
        related_name='tests',
        related_query_name='test',
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tester:test', kwargs={"pk": self.pk})

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'
        ordering = ['category', 'name']


class Question(models.Model):
    class QuestionType(models.TextChoices):
        FREE_ANSWER = 'FA', _('Свободный ответ')
        ONE_ANSWER = 'OA', _('Один вариант ответа')
        MANY_ANSWERS = 'MA', _('Несколько вариантов ответа')

    description = models.CharField(_('Описание'), max_length=150, blank=True)
    image = models.ImageField(
        _('Картинка'),
        upload_to='img/question_images',
        height_field=None, width_field=None,
        max_length=None,
        blank=True, null=True
    )
    text = models.TextField(_('Текст вопроса'), blank=True)
    test_instance = models.ForeignKey(TestInstance, on_delete=models.CASCADE,
        related_name='questions',
        related_query_name='question',
        verbose_name='Тест',
    )
    number = models.IntegerField(_('Номер'), default=-1, editable=False)
    cost = models.IntegerField(_('Стоимость'), default=0)

    def qtype(self):
        correct_answers = self.choices.filter(is_correct=True).count()
        if correct_answers == 0:
            return 'FA'
        if correct_answers == 1:
            return 'OA'
        return 'MA'
    qtype.short_description = 'Тип вопроса'

    def save(self, *args, **kwargs):
        if self.number == -1:
            self.number = self.test_instance.questions.count() + 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for question in self.test_instance.questions.filter(number__gt=self.number):
            question.number -= 1
            question.save()
            print(question.number)
        super().delete(*args, **kwargs)

    def __str__(self):
        return '%s, Вопрос № %s' % (self.test_instance.name, self.number)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
        ordering = ['test_instance', 'pk']


class QuestionChoice(models.Model):
    text = models.CharField(_('Текст'), max_length=120)
    is_correct = models.BooleanField(_('Правильный'))
    question = models.ForeignKey(Question, on_delete=models.CASCADE,
        related_name='choices',
        related_query_name='choice',
    )
    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответа'

src/tester/forms.py
from django import forms

class QuestionChoiceForm(forms.ModelForm):
    class Meta:
        widgets = {
            'text': forms.TextInput(attrs={'size': 180}),
            'is_correct': forms.CheckboxInput()
        }

src/mainpage/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = "mainpage/index.html"

src/tester/views.py
from django.shortcuts import render
from . import models

from django.views.generic import TemplateView, DetailView, ListView

class TestPageView(TemplateView):
    template_name = 'tester/test.html'

class TestDetailView(DetailView):
    model = models.TestInstance
    context_object_name = 'test'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['category'] = models.TestCategory.objects.get(slug=self.kwargs['category_slug'])
        context['questions'] = self.get_object().questions.all()
        return context

class CategoriesView(ListView):
    template_name = 'tester/categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return models.TestCategory.objects.all()


class TestByCategoryView(ListView):
    template_name = 'tester/by_category.html'
    context_object_name = 'tests'

    def get_queryset(self):
        return models.TestInstance.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['category'] = models.TestCategory.objects.get(slug=self.kwargs['category_slug'])
        return context

src/mainpage/templates/mainpage/index.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block title %}Test system{% endblock title %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/mainpage_main.css' %}">
{% endblock styles %}

{% block content %}

{% endblock content %}


{% block scripts %}
	<script src="{% static 'js/mainpage_main.js' %}"></script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{% block title %}{% endblock title %}</title>

	{% block styles %}
	{% endblock styles %}

</head>
<body>

	{% block header %}
		<h1>Test system by Kayta and Zh</h1>
	{% endblock header %}

	{% block content %}
	{% endblock content %}


{% block scripts %}
{% endblock scripts %}
</body>
</html>

src/tester/templates/tester/by_category.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block title %}{{ category.name }}{% endblock title %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/tester_tmp.css' %}">
{% endblock styles %}

{% block content %}

<div class="lev-1">
	<ul class="lev-2">
		<li><a href="{% url 'tester:categories' %}">Категории</a></li>
	</ul>
	<p>Тесты категории {{ category }}:</p>
	{% for test in tests %}
		<div class="lev-2">
			<a href="{% url 'tester:test' category.slug test.pk %}">{{ test.name }}</a>
		</div>
	{% endfor %}
</div>


{% endblock content %}

{% block scripts %}
	{% comment %} <script src="{% static 'js/tester_main.js' %}"></script> {% endcomment %}
{% endblock scripts %}

src/tester/templates/tester/categories.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block title %}Категории{% endblock title %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/tester_tmp.css' %}">
{% endblock styles %}

{% block content %}

<div class="lev-1">
	{% for category in categories %}
		<div class="lev-2">
			<a href="{% url 'tester:category' category.slug %}">{{ category }}</a>
		</div>
	{% endfor %}
</div>


{% endblock content %}

{% block scripts %}
	{% comment %} <script src="{% static 'js/tester_main.js' %}"></script> {% endcomment %}
{% endblock scripts %}

src/tester/templates/tester/test.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>

	<link rel="stylesheet" href="{% static 'css/tester_main.css' %}">
</head>
<body>


	<div class="test-wrapper">

	</div>

	<script>

	</script>

	<script src="{% static 'js/tester_main.js' %}"></script>
</body>
</html>

src/tester/templates/tester/testinstance_detail.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block title %}{{ test }}{% endblock title %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/tester_tmp.css' %}">
{% endblock styles %}

{% block content %}

<div class="lev-1">
	<ul class="lev-2 breadcrumbs">
		<li><a href="{% url 'tester:categories' %}">Категории</a></li>
		<li><a href="{% url 'tester:category' category.slug %}">{{ category }}</a></li>
	</ul>
	<h2>{{ test.name }}</h2>
	{% for question in questions %}
		<div class="lev-2">
			<p>{{ question }}</p>
			<p class="lev-3">{{ question.text }}</p>
		</div>
	{% endfor %}
</div>

{% endblock content %}

{% block scripts %}
	{% comment %} <script src="{% static 'js/tester_main.js' %}"></script> {% endcomment %}
{% endblock scripts %}